[project]
name = "annotation_interface"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "deepeval>=3.7.9",
    "gradio>=5.42.0",
    "psycopg2-binary>=2.9.0",
    "sqlalchemy>=2.0.0",
]
